name: updata_restart.yml
on: push

jobs:
  updata_restart:
    runs-on: ubuntu-22.04
    steps:
      - name: print name repository
        #updata project and restart
        run: ${{ github.repository_name }}
#        uses: appleboy/ssh-action@v1
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USERNAME }}
#          key: ${{ secrets.KEY }}
#          script: |
#            cd ${{ github.repository_name }}
#            git pull
#            sudo systemctl stop ${{ github.repository_name }}
#            sudo systemctl daemon-reload
#            sudo systemctl start ${{ github.repository_name }}
